# Generated by Django 4.2.11 on 2024-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='last_viewer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
