# Generated by Django 4.2.11 on 2024-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Hobbies', 'Hobbies'), ('Food', 'Food'), ('Programming', 'Programming')], default='Hobbies', max_length=20),
        ),
    ]
